spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=socapp
spring.datasource.username=sa
spring.datasource.password=Stroengpesswurd1?
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbg==
jwt.expiration=86400000
