# Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=socapp
spring.datasource.username=sa
spring.datasource.password=StroengPesswurd1?
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Flyway Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true